# Generated file that can be used to preload variant images
set(BOARD "nrf52833dk_nrf52833" CACHE INTERNAL "NCS child image controlled")
set(BOARD_ROOT "c:/users/user/onedrive/desktop/nrf_dongle/light_switch_1;C:/nRC-SDK/v2.4.2/nrf;C:/nRC-SDK/v2.4.2/zephyr" CACHE INTERNAL "NCS child image controlled")
set(CACHED_CONF_FILE "c:/Users/User/OneDrive/Desktop/nrf_dongle/light_switch_1/prj.conf" CACHE INTERNAL "NCS child image controlled")
set(CONF_FILE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE "boards/nrf52833dk_nrf52833.overlay" CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE "boards/nrf52833dk_nrf52833.overlay" CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION "NONE" CACHE INTERNAL "NCS child image controlled")
set(OVERLAY_CONFIG "boards/nrf52833dk_nrf52833.conf" CACHE INTERNAL "NCS child image controlled")
set(WEST_PYTHON "C:/toolchains/31f4403e35/opt/bin/python.exe" CACHE INTERNAL "NCS child image controlled")
